### ISSUE TITLE
no option for setting replica/shard count in a single place, from `conf/sarjitsu.conf`

### ISSUE THREAD

**Issue by arcolife** [distributed-system-analysis/sarjitsu#26]
1. We need options `SHARD_COUNT=` and `REPLICAS_COUNT=` under `conf/sarjitsu.conf.example` so that these could be utilized under `lib/{backend,middleware}` as is present in their launching scripts  `lib/backend/launch_backend` and `lib/middleware/launch_api_server`
   
   For example, `lib/backend/launch_backend` contains the following lines:
   
   ``` sh
   sed -i -r 's#^number_of_shards\s?=.*#number_of_shards = '$SHARD_COUNT'#g' conf/sar-index.cfg
   sed -i -r 's#^number_of_replicas\s?=.*#number_of_replicas = '$REPLICAS_COUNT'#g' conf/sar-index.cfg
   ```
   
   But since the variables *_COUNT were never  present in `conf/sarjitsu.conf.example` file,  above mentioned sed changes leave the following lines empty in `lib/{backend,middleware}/conf/sar-index.cfg.example`:
   
   ```
   number_of_shards = 
   number_of_replicas = 
   ```
2. Also, add an option in the respective launch scripts, to completely remove these lines in config files copied inside containers of middleware and backend, so that if the user doesn't supply any values to *_COUNT, then it implies that the user had chosen to use default elasticsearch settings for his/her setup.

**Comment by portante** [comment]
If these values feed the construction of the index templates, why not make them `.yml` files that are used to construct the index template directly?  Do we need to have `sed` to edit the files when the user can just consider these config files.

**Comment by arcolife** [comment]
because for UX purpose, I had the user enter everything in a common config file, bundled together, under `conf/sarjitsu.conf.example`. So that the user doesn't have to manage multiple config files everytime they deploy this, or make changes in multiple files, because we have multiple containers using similar kinds of config files (with few differences).

**Comment by arcolife** [comment]
fixed in latest version. https://github.com/distributed-system-analysis/sarjitsu/commit/b6dba1a2505114db8a570197c6a46c62d2ea8a9f#diff-005950e1aff25afa320a11650c8979d6R44
