### ISSUE TITLE
use timeshifting feature to compare 2 different sa binaries

### ISSUE THREAD

**Issue by arcolife** [distributed-system-analysis/sarjitsu#28]
Given that Grafana-Elasticsearch has a timeshift feature added in future (references below), add option in sarjitsu to specify whether the files being uploaded, should be compared with timeshift feature.

For this, gotta bump up elasticsearch version used by sarjitsu (currently 1.7.3)

references: 
- Open issue: Metaqueries for timeshift https://github.com/grafana/grafana/issues/3677
- Different timeshift on same panel  https://github.com/grafana/grafana/issues/2093#issuecomment-163603728
- Serial Differencing pipeline aggregations in ES https://github.com/elastic/elasticsearch/pull/11196

**Comment by SeriousM** [comment]
The feature on elastic (elastic/elasticsearch#11196) is merged. 

>For this, gotta bump up elasticsearch version used by sarjitsu (currently 1.7.3)

whats the status on this point?

**Comment by arcolife** [comment]
oh okay. Seems like a low hanging fruit. Will fix this asap.

High priorities:
- fixing that grafana PR (mentioned in [1])
- getting the framework dependencies up to speed with newer versions.

[1] - https://github.com/arcolife/sarjitsu/issues/11#issuecomment-319862757

@SeriousM Please let me know if you're or someone you know, is willing to collaborate. Or else let me find some time to do this soon. High time! :)

**Comment by SeriousM** [comment]
Thank you for your swift response! I guess I can't help you with this, I just was on the search for the timeshift feature for elastic datasources in grafana and found this issue here.
I thought asking for the status might get things going :)

**Comment by arcolife** [comment]
alrighty then. Thanks for stopping by :rofl:

**Comment by nfw999** [comment]
We use this plugin to solve the problem and hope to help you.
[graph-compare-panel](https://github.com/AutohomeCorp/graph-compare-panel)
![Screenshot1](https://raw.githubusercontent.com/AutohomeCorp/graph-compare-panel/master/dist/screenshots/image-1.png)
![Screenshot1](https://raw.githubusercontent.com/AutohomeCorp/graph-compare-panel/master/dist/screenshots/image-2.png)

**Comment by psuriset** [comment]
@nfw999  Can you please send PR
