### ISSUE TITLE
problem! Dashboard not found error when navigated to grafana

### ISSUE THREAD

**Issue by adasmala** [distributed-system-analysis/sarjitsu#29]
Im using the default parameters and ran setup.sh
vizit upload went fine. but after login to grafana,  when i browse and select hostname-1_date_investigation named dashboard in drop down it throws this error 
"problem!  Dashboard not found error"

can someone help please.

[root@pup sarjitsu-master]# ./vizit -f /sar-logs/sa28
[11/29/16 05:56:14 CST] - Single file mode selected..
[11/29/16 05:56:14 CST] - attempting to upload file(s) to 172.17.0.6:80/upload/ now..
[11/29/16 05:56:14 CST] - Current connection TIMEOUT value: 10 seconds..
[11/29/16 05:56:16 CST] - Files uploaded successfully..
+--------+----------+----------+-------------+-----------------------+-----------------------+
| Status | Filename | Platform |   Nodename  |         Begin         |          End          |
+--------+----------+----------+-------------+-----------------------+-----------------------+
|  True  |   sa28   |    5x    | hostname-1 | 06:10:01, 28 Nov 2016 | 05:50:01, 29 Nov 2016 |
+--------+----------+----------+-------------+-----------------------+-----------------------+
Grafana Dashboard at: http://172.17.0.4:3000/
Login with your Grafana credentials. [Default: (admin/admin)]

**Comment by arcolife** [comment]
Hey @adasmala, thanks for trying out sarjitsu! Glad it worked for you up to the upload part. 

To check if all the services are healthy, could you gist paste the output for each of the following commands ? Most probably you'll see something weird by yourself in the output. 

```
1. docker exec -it server_jitsu cat sarjitsu_app.log

2. docker exec -it  api_jitsu  systemctl  status metadata_creation

3. $ docker exec -it api_jitsu bash
   # journalctl -xe | grep run.py

4. $ docker exec -it grafana_jitsu bash 
   # journalctl -xe | grep grafana

5. $ docker exec -it  elastic_jitsu  bash
   # journalctl -xe | grep elastic

6. $ docker exec -it server_jitsu bash
   # journalctl -xe | grep uwsgi
```

**Comment by adasmala** [comment]
Hey Archit,

Thank you for the reply and instructions.
The problem seems to be with the grafana dashboard page not existing in db?
FYI,  for grafana dashboard i'm connecting to the proxied port on host i.e 9602 port instead of http://172.17.0.4:3000/

Here is the result, please check when you get a chance and advice
[root@ppthost sarjitsu-master]# docker exec -it server_jitsu cat sarjitsu_app.log
docker exec -it  api_jitsu  systemctl  status metadata_creation
docker exec -it api_jitsu bash[2016-12-06 16:14:27,254] {./extract_sa.py:58} WARNING - =====Running alternate ES indexing script======
[2016-12-06 16:14:27,254] {./extract_sa.py:59} WARNING - No active exception to reraise
[2016-12-06 16:16:18,502] {./extract_sa.py:58} WARNING - =====Running alternate ES indexing script======
[2016-12-06 16:16:18,502] {./extract_sa.py:59} WARNING - No active exception to reraise


[root@ppthost sarjitsu-master]#  docker exec -it api_jitsu bash
[root@a71efa9d2a00 /]# journalctl -xe | grep run.py
Dec 06 16:13:01 a71efa9d2a00 run.py[167]: * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
Dec 06 16:14:31 a71efa9d2a00 run.py[167]: 172.17.0.6 - - [06/Dec/2016 16:14:31] "POST /db/create/ HTTP/1.1" 200 -
Dec 06 16:16:19 a71efa9d2a00 run.py[167]: 172.17.0.6 - - [06/Dec/2016 16:16:19] "POST /db/create/ HTTP/1.1" 200 -
[root@a71efa9d2a00 /]# exit


[root@ppthost sarjitsu-master]# docker exec -it grafana_jitsu bash
[root@61871fb1d71e /]# journalctl -xe | grep grafana
Dec 06 16:12:51 61871fb1d71e systemd[1]: Started Starts and stops a single grafana instance on this system.
-- Subject: Unit grafana-server.service has finished start-up
-- Unit grafana-server.service has finished starting up.
Dec 06 16:12:51 61871fb1d71e systemd[1]: Starting Starts and stops a single grafana instance on this system...
-- Subject: Unit grafana-server.service has begun start-up
-- Unit grafana-server.service has begun starting up.
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:51 [I] Starting Grafana
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:51 [I] Version: 3.0.1, Commit: v3.0.1+2-g549eb15, Build date: 2016-05-11 08:37:21 +0000 UTC
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:51 [I] Configuration Info
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: Config files:
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: [0]: /usr/share/grafana/conf/defaults.ini
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: [1]: /etc/grafana/grafana.ini
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: Command lines overrides:
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: [0]: default.paths.data=/var/lib/grafana
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: [1]: default.paths.logs=/var/log/grafana
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: [2]: default.paths.plugins=/var/lib/grafana/plugins
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: Paths:
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: home: /usr/share/grafana
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: data: /var/lib/grafana
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: logs: /var/log/grafana
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: plugins: /var/lib/grafana/plugins
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:51 [I] Database: postgres
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:51 [I] Migrator: Starting DB migration
Dec 06 16:12:51 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:51 [I] Migrator: exec migration id: create migration_log table
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create user table
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: add unique index user.login
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: add unique index user.email
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: drop index UQE_user_login - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: drop index UQE_user_email - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: Rename table user to user_v1 - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create user table v2
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index UQE_user_login - v2
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index UQE_user_email - v2
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: copy data_source v1 to v2
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: Drop old table user_v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create temp user table v1-7
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index IDX_temp_user_email - v1-7
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index IDX_temp_user_org_id - v1-7
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index IDX_temp_user_code - v1-7
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index IDX_temp_user_status - v1-7
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create star table
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: add unique index star.user_id_dashboard_id
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create org table v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index UQE_org_name - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create org_user table v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index IDX_org_user_org_id - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index UQE_org_user_org_id_user_id - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: copy data account to org
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: skipping migration id: copy data account to org, condition not fulfilled
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: copy data account_user to org_user
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: skipping migration id: copy data account_user to org_user, condition not fulfilled
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: Drop old table account
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: Drop old table account_user
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create dashboard table
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: add index dashboard.account_id
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: add unique index dashboard_account_id_slug
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create dashboard_tag table
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: add unique index dashboard_tag.dasboard_id_term
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: drop index UQE_dashboard_tag_dashboard_id_term - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: Rename table dashboard to dashboard_v1 - v1
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create dashboard v2
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index IDX_dashboard_org_id - v2
Dec 06 16:12:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:52 [I] Migrator: exec migration id: create index UQE_dashboard_org_id_slug - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: copy dashboard v1 to v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop table dashboard_v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: alter dashboard.data to mediumtext v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Add column updated_by in dashboard - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Add column created_by in dashboard - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create data_source table
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: add index data_source.account_id
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: add unique index data_source.account_id_name
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop index IDX_data_source_account_id - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop index UQE_data_source_account_id_name - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Rename table data_source to data_source_v1 - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create data_source table v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index IDX_data_source_org_id - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_data_source_org_id_name - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: copy data_source v1 to v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Drop old table data_source_v1 #2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Add column with_credentials
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create api_key table
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: add index api_key.account_id
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: add index api_key.key
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: add index api_key.account_id_name
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop index IDX_api_key_account_id - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop index UQE_api_key_key - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop index UQE_api_key_account_id_name - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Rename table api_key to api_key_v1 - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create api_key table v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index IDX_api_key_org_id - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_api_key_key - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_api_key_org_id_name - v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: copy api_key v1 to v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Drop old table api_key_v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create dashboard_snapshot table v4
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop table dashboard_snapshot_v4 #1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create dashboard_snapshot table v5 #2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v5
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: alter dashboard_snapshot to mediumtext v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create quota table v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_quota_org_id_user_id_target - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create plugin_setting table
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create index UQE_plugin_setting_org_id_plugin_id - v1
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create session table
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Drop old table playlist table
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: Drop old table playlist_item table
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create playlist table v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create playlist item table v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop preferences table v2
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: drop preferences table v3
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Migrator: exec migration id: create preferences table v3
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Created default admin user: admin
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Plugins: Scan starting
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [W] Plugins: Plugin dir /var/lib/grafana/plugins does not exist
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Plugins: Plugin dir /var/lib/grafana/plugins created
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [T] Checking for updates
Dec 06 16:12:53 61871fb1d71e grafana-server[152]: 2016/12/06 16:12:53 [I] Listen: http://0.0.0.0:3000
Dec 06 16:14:41 61871fb1d71e grafana-server[152]: 2016/12/06 16:14:41 [I] Completed x.x.x.x admin "GET /dashboard/db/host-one052320 HTTP/1.1" 302 Found 29 bytes in 4653us
Dec 06 16:14:41 61871fb1d71e grafana-server[152]: 2016/12/06 16:14:41 [T] auto-login cookie cleared: admin
Dec 06 16:14:52 61871fb1d71e grafana-server[152]: 2016/12/06 16:14:52 [I] Completed x.x.x.x admin "GET /api/dashboards/db/host-one052320 HTTP/1.1" 404 Not Found 33 bytes in 3681us
Dec 06 16:14:57 61871fb1d71e grafana-server[152]: 2016/12/06 16:14:57 [I] Completed x.x.x.x admin "GET /api/dashboards/db/host-one05431 HTTP/1.1" 404 Not Found 33 bytes in 4757us
Dec 06 16:15:46 61871fb1d71e grafana-server[152]: 2016/12/06 16:15:46 [I] Completed x.x.x.x admin "GET /api/dashboards/db/host-one05431 HTTP/1.1" 404 Not Found 33 bytes in 3678us
[root@61871fb1d71e /]# exit

[root@ppthost sarjitsu-master]# docker exec -it  elastic_jitsu  bash
[root@5b261eef5732 /]# journalctl -xe | grep elastic
-- Subject: Unit elasticsearch.service has finished start-up
-- Unit elasticsearch.service has finished starting up.
-- Subject: Unit elasticsearch.service has begun start-up
-- Unit elasticsearch.service has begun starting up.
[root@5b261eef5732 /]# exit
exit



[root@ppthost sarjitsu-master]# docker exec -it server_jitsu bash
[root@10c6ded1f160 src]# journalctl -xe | grep uwsgi
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: [uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: *** Starting uWSGI 2.0.14 (64bit) on [Tue Dec  6 16:13:03 2016] ***
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 29 November 2016 08:18:18
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: os: Linux-3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: nodename: 10c6ded1f160
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: machine: x86_64
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: clock source: unix
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: detected number of CPU cores: 1
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: current working directory: /opt/sarjitsu/src
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: detected binary path: /usr/bin/uwsgi
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: !!! no internal routing support, rebuild with pcre support !!!
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: chdir() to /opt/sarjitsu/src/
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: your processes number limit is 1048576
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: your memory page size is 4096 bytes
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: detected max file descriptor number: 1048576
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: lock engine: pthread robust mutexes
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: thunder lock: disabled (you can enable it with --thunder-lock)
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: uwsgi socket 0 bound to UNIX address /opt/sarjitsu/src/flaskapp.sock fd 3
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: uWSGI running as root, you can use --uid/--gid/--chroot options
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Dec 06 16:13:03 10c6ded1f160 uwsgi[186]: Python version: 3.4.3 (default, Aug  9 2016, 15:36:17)  [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: *** Python threads support is disabled. You can enable it with --enable-threads ***
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: Python main interpreter initialized at 0xbe0450
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: your server socket listen backlog is limited to 100 connections
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: your mercy for graceful operations on workers is 60 seconds
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: mapped 436560 bytes (426 KB) for 5 cores
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: *** Operational MODE: preforking ***
Dec 06 16:13:04 10c6ded1f160 uwsgi[186]: added /usr/bin/python3 to pythonpath.
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xbe0450 pid: 186 (default app)
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: *** uWSGI is running in multiple interpreter mode ***
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: spawned uWSGI master process (pid: 186)
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: spawned uWSGI worker 1 (pid: 199, cores: 1)
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: spawned uWSGI worker 2 (pid: 200, cores: 1)
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: spawned uWSGI worker 3 (pid: 201, cores: 1)
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: spawned uWSGI worker 4 (pid: 202, cores: 1)
Dec 06 16:13:06 10c6ded1f160 uwsgi[186]: spawned uWSGI worker 5 (pid: 203, cores: 1)
Dec 06 16:14:04 10c6ded1f160 uwsgi[186]: ./server.py:62: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
Dec 06 16:14:04 10c6ded1f160 uwsgi[186]: form = UploadForm(request.form)
Dec 06 16:14:04 10c6ded1f160 uwsgi[186]: [pid: 199|app: 0|req: 1/1] x.x.x.x () {48 vars in 1201 bytes} [Tue Dec  6 16:14:04 2016] POST /upload/ => generated 29 bytes in 31 msecs (HTTP/1.1 200) 3 headers in 175 bytes (6 switches on core 0)
Dec 06 16:14:09 10c6ded1f160 uwsgi[186]: ./server.py:114: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
Dec 06 16:14:09 10c6ded1f160 uwsgi[186]: form = UploadForm(request.form)
Dec 06 16:14:09 10c6ded1f160 uwsgi[186]: [pid: 203|app: 0|req: 1/2] x.x.x.x () {40 vars in 921 bytes} [Tue Dec  6 16:14:09 2016] GET /upload/ => generated 6971 bytes in 43 msecs (HTTP/1.1 200) 3 headers in 185 bytes (1 switches on core 0)
Dec 06 16:14:27 10c6ded1f160 uwsgi[186]: ./server.py:62: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
Dec 06 16:14:27 10c6ded1f160 uwsgi[186]: form = UploadForm(request.form)
Dec 06 16:14:31 10c6ded1f160 uwsgi[186]: [pid: 199|app: 0|req: 2/3] x.x.x.x () {46 vars in 1171 bytes} [Tue Dec  6 16:14:27 2016] POST /upload/ => generated 4292 bytes in 4677 msecs (HTTP/1.1 200) 3 headers in 185 bytes (5 switches on core 0)
Dec 06 16:16:18 10c6ded1f160 uwsgi[186]: ./server.py:62: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
Dec 06 16:16:18 10c6ded1f160 uwsgi[186]: form = UploadForm(request.form)
Dec 06 16:16:19 10c6ded1f160 uwsgi[186]: [pid: 199|app: 0|req: 3/4] x.x.x.x () {48 vars in 1202 bytes} [Tue Dec  6 16:16:18 2016] POST /upload/ => generated 4292 bytes in 1337 msecs (HTTP/1.1 200) 3 headers in 185 bytes (4 switches on core 0)
Dec 06 16:16:20 10c6ded1f160 uwsgi[186]: [pid: 203|app: 0|req: 2/5] x.x.x.x () {46 vars in 1058 bytes} [Tue Dec  6 16:16:20 2016] GET /static/js/bootstrap.min.js => generated 0 bytes in 4 msecs (HTTP/1.1 304) 5 headers in 287 bytes (0 switches on core 0)
Dec 06 16:16:20 10c6ded1f160 uwsgi[186]: [pid: 202|app: 0|req: 1/6] x.x.x.x () {46 vars in 1070 bytes} [Tue Dec  6 16:16:20 2016] GET /static/css/bootstrap.css => generated 0 bytes in 15 msecs (HTTP/1.1 304) 5 headers in 288 bytes (0 switches on core 0)
Dec 06 16:16:20 10c6ded1f160 uwsgi[186]: [pid: 200|app: 0|req: 1/7] x.x.x.x () {46 vars in 1091 bytes} [Tue Dec  6 16:16:20 2016] GET /static/css/bootstrap-responsive.css => generated 0 bytes in 12 msecs (HTTP/1.1 304) 5 headers in 287 bytes (0 switches on core 0)

**Comment by arcolife** [comment]
@adasmala try again after pulling the latest code? I've changed the structure of this framework and this issues should be obsolete by now; I'm now using docker-compose which manages the microservices much more efficiently, as compared to the scripts we were using earlier. Please follow the new README for installation. thanks!

**Comment by adasmala** [comment]
Hi archit,

Thank you for the update. I installed the latest version.
It looks good. Only issue I see is cpu all stats are not gettign generated
in grafana screen. Other than that all are ok.
Thansk again for your work.

**Comment by arcolife** [comment]
@adasmala great! Nice to see it working for you. Also, please see https://github.com/grafana/grafana/pull/4694 

cpu docs come under 'nested docs' category. This is actually a problem with grafana's ES connector plugin; the support for which was submitted in a PR, referenced in the issue #12. Any advancement on that front means win for sarjitsu. thanks!

**Comment by adasmala** [comment]
Archit,  Thanks for explaining that. Is there a simple easy way to delete
all the existing dashboards from grafana?
The reason I ask is when I run vizit twice on the same file, it shows up
two dashboard files with same name in grafana UI.
I think I can delete the indexes in Elastic search through DEL api. But Not
sure how to do it for multiple dashboards in grafana.
or Does it need to be deleted from postgres. Please suggest when you can.I
can open an issue in github for this if you prefer that.

**Comment by thecreed** [comment]
Hi Adasmala,
i've wrote a python script that does exactly that :)
https://github.com/thecreed/sarjitsu/blob/master/utils/grafana_cleaner.py
you just need  
1: replace the grafana API key with your own.
2:  update the regex for the dashboard names:
  gr.delete_multiple_dashboards('.*(bi-|DevOps-).*')


arcolife - i'll create PR for it..

**Comment by adasmala** [comment]
Perfect. Much Appreciated Jhonny and arcofile. I'll test it.

**Comment by arcolife** [comment]
@thecreed waiting for it :) :100: thanks!
