### ISSUE TITLE
collect sar files from remote servers and load them to elasticsearch

### ISSUE THREAD

**Issue by thecreed** [distributed-system-analysis/sarjitsu#31]
could be implemented using ansible playbook's.

**Comment by arcolife** [comment]
@thecreed hey, yes that could added as a functionality to 'vizit' tool. If you're working on this, would you be willing to submit a PR? thanks! let me know.

**Comment by arcolife** [comment]
Not sure if this should be an 'enhancement'. Collecting sar files from different servers means having to maintain an inventory if using ansible playbooks. IMHO orchestration of how one gathers input for sarjitsu is out of scope of this project. Per se, this could mean providing remote connection details for collecting sar files. 

Closing this as per the aforementioned reasoning. Feel free to reopen/discuss this whenever.
