### ISSUE TITLE
vizit  error after upload

### ISSUE THREAD

**Issue by thecreed** [distributed-system-analysis/sarjitsu#32]
Although files uploaded successfully to Elasticsearch ,

output error is given:
[root@localhost sarjitsu]# ./vizit -d sar/sa/
[01/23/17 13:45:26 GMT] - Directory mode selected..
[01/23/17 13:45:26 GMT] - attempting to upload file(s) to 196.168.200.6:80/upload/ now..
[01/23/17 13:45:26 GMT] - Current connection TIMEOUT value: 10 seconds..

[01/23/17 13:46:53 GMT] - **Files uploaded successfully.**.
Traceback (most recent call last):
  File "./utils/vizit_results_parser.py", line 29, in <module>
    result = json.loads(input())
  File "/usr/lib64/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

docker exec -ti server_jitsu bash
[root@546578cd7d4a src]# journalctl  | tail -30
Jan 23 13:45:55 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:55,696] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:55 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:55,760] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar24
Jan 23 13:45:55 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:55,761] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,015] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar01
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,018] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,078] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar21
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,078] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,150] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar09
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,151] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,275] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar16
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,276] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,409] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar03
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,410] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,729] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar18
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,730] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,839] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar02
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,840] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,900] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar17
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,901] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,918] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar04
Jan 23 13:45:56 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:56,919] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,148] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar11
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,148] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,159] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar06
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,160] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,357] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar30
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,358] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,421] ERROR in data_processor: Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar29
Jan 23 13:45:57 546578cd7d4a uwsgi[143]: [2017-01-23 13:45:57,422] ERROR in data_processor: SAR data extraction *failed*!
Jan 23 13:46:53 546578cd7d4a uwsgi[143]: [pid: 150|app: 0|req: 1/1] 196.168.200.1 () {36 vars in 597 bytes} [Mon Jan 23 13:46:53 2017] GET /upload/ => generated 68237 bytes in 14 msecs via sendfile() (HTTP/1.1 200) 7 headers in 267 bytes (0 switches on core 0)

**Comment by arcolife** [comment]
@thecreed the results parser produced an error. I see that the data procesor failed as well. Says "Invalid system activity file: safiles/a578baa2-a9fb-4ccf-8a43-7b6bb34ce1fb/sar11"

Please notice that this is a 'SARxx' file, not a binary 'SAxx' file. /var/log/sa/ contains both sar and sa files. I get that there's an error on vizit's result parser, but that's probably a case of exception handling in vizit, but not an issue with sarjitsu, it seems.

Would you be willing to provide output of https://github.com/distributed-system-analysis/sarjitsu/blob/master/utils/vizit#L84 (could you edit that locally in your clone, and instead of piping it to `./vizit_results_parser.py`, maybe dump it in a file ?) thanks!

**Comment by arcolife** [comment]
added error handling in https://github.com/distributed-system-analysis/sarjitsu/commit/df7c5d7b7ac9951800a4831c3d4a6e395e05d126

Please reopen with relevant logs as produced from aforementioned fix. Closing this for now.
