### ISSUE TITLE
after  docker restart  ./restart_sarjitsu  sarjitsu_backend is not  started correctly

### ISSUE THREAD

**Issue by thecreed** [distributed-system-analysis/sarjitsu#33]
from journalctl:
[root@546578cd7d4a src]# journalctl -f
-- Logs begin at Mon 2017-01-23 10:31:02 UTC. --
Jan 25 13:40:39 546578cd7d4a uwsgi[81]: --- no python application found, check your startup logs for errors ---
Jan 25 13:40:39 546578cd7d4a uwsgi[81]: [pid: 85|app: -1|req: -1/1] 196.168.200.1 () {36 vars in 588 bytes} [Wed Jan 25 13:40:39 2017] POST /upload/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Jan 25 13:40:43 546578cd7d4a uwsgi[81]: --- no python application found, check your startup logs for errors ---
Jan 25 13:40:43 546578cd7d4a uwsgi[81]: [pid: 86|app: -1|req: -1/2] 196.168.200.1 () {36 vars in 588 bytes} [Wed Jan 25 13:40:43 2017] POST /upload/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Jan 25 13:40:43 546578cd7d4a uwsgi[81]: --- no python application found, check your startup logs for errors ---
Jan 25 13:40:43 546578cd7d4a uwsgi[81]: [pid: 86|app: -1|req: -1/3] 196.168.200.1 () {36 vars in 588 bytes} [Wed Jan 25 13:40:43 2017] POST /upload/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Jan 25 13:40:44 546578cd7d4a uwsgi[81]: --- no python application found, check your startup logs for errors ---
Jan 25 13:40:44 546578cd7d4a uwsgi[81]: [pid: 84|app: -1|req: -1/4] 196.168.200.1 () {36 vars in 588 bytes} [Wed Jan 25 13:40:44 2017] POST /upload/ => generated 21 bytes in 5 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
Jan 25 13:40:45 546578cd7d4a uwsgi[81]: --- no python application found, check your startup logs for errors ---
Jan 25 13:40:45 546578cd7d4a uwsgi[81]: [pid: 87|app: -1|req: -1/5] 196.168.200.1 () {36 vars in 588 bytes} [Wed Jan 25 13:40:45 2017] POST /upload/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

its solved only by systemd restart :
systemctl restart sarjitsu.service

**Comment by arcolife** [comment]
could you try to reproduce this with the new docker-compose based structure? please see https://github.com/distributed-system-analysis/sarjitsu/issues/30#issuecomment-276234408

thanks!

**Comment by arcolife** [comment]
verified with `docker-compose restart` as well as: 
```
docker-compose stop
docker-compose start
```
